services:
  - mysql
before_install:
  - mysql -e 'create database test_db;'

install:
  - cd api/ && composer install --prefer-dist --no-interaction
  - php novice migrate
  - php novice seed

language: php

after_script:
 - php vendor/bin/coveralls -v

notifications:
  email: false
